sonar.projectKey=alexnec29_CampusEats
sonar.organization=alexnec29

sonar.sources=CampusEats.Api,campuseats.client/src
sonar.tests=CampusEats.Test
sonar.exclusions=**/node_modules/**,**/bin/**,**/obj/**,**/Migrations/**
sonar.test.exclusions=**/*.Test/**
