// <auto-generated />
using System;
using CampusEats.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CampusEats.Api.Migrations
{
    [DbContext(typeof(CampusEatsDbContext))]
    partial class CampusEatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CampusEats.Api.Models.AdminProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("admin_profile");
                });

            modelBuilder.Entity("CampusEats.Api.Models.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Allergens", (string)null);
                });

            modelBuilder.Entity("CampusEats.Api.Models.BuyerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("buyer_profile");
                });

            modelBuilder.Entity("CampusEats.Api.Models.Jwt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BlackListTokens");
                });

            modelBuilder.Entity("CampusEats.Api.Models.KitchenProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("kitchen_profile");
                });

            modelBuilder.Entity("CampusEats.Api.Models.KitchenTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssignedStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("KitchenTasks", (string)null);
                });

            modelBuilder.Entity("CampusEats.Api.Models.LoyaltyAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsBalance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LoyaltyAccounts", (string)null);
                });

            modelBuilder.Entity("CampusEats.Api.Models.LoyaltyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("LoyaltyAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("LoyaltyAccountId");

                    b.ToTable("LoyaltyTransactions", (string)null);
                });

            modelBuilder.Entity("CampusEats.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems", (string)null);
                });

            modelBuilder.Entity("CampusEats.Api.Models.MenuItemAllergen", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("AllergenId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("MenuItemId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("MenuItemAllergens", (string)null);
                });

            modelBuilder.Entity("CampusEats.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("CampusEats.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("CampusEats.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("CampusEats.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("CampusEats.Api.Models.BuyerProfile", b =>
                {
                    b.OwnsOne("CampusEats.Api.Models.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("BuyerProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("building")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("city")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("county")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BuyerProfileId");

                            b1.ToTable("buyer_profile");

                            b1.WithOwner()
                                .HasForeignKey("BuyerProfileId");
                        });

                    b.Navigation("DeliveryAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("CampusEats.Api.Models.KitchenProfile", b =>
                {
                    b.OwnsOne("CampusEats.Api.Models.Address", "KitchenAddress", b1 =>
                        {
                            b1.Property<Guid>("KitchenProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("building")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("city")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("county")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("street")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("KitchenProfileId");

                            b1.ToTable("kitchen_profile");

                            b1.WithOwner()
                                .HasForeignKey("KitchenProfileId");
                        });

                    b.OwnsOne("CampusEats.Api.Models.WeeklyWorkingHours", "WeeklyWorkingHours", b1 =>
                        {
                            b1.Property<Guid>("KitchenProfileId")
                                .HasColumnType("uuid");

                            b1.HasKey("KitchenProfileId");

                            b1.ToTable("kitchen_profile");

                            b1.WithOwner()
                                .HasForeignKey("KitchenProfileId");

                            b1.OwnsOne("CampusEats.Api.Models.WorkingHours", "Friday", b2 =>
                                {
                                    b2.Property<Guid>("WeeklyWorkingHoursKitchenProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("Close")
                                        .HasColumnType("interval");

                                    b2.Property<TimeSpan>("Open")
                                        .HasColumnType("interval");

                                    b2.HasKey("WeeklyWorkingHoursKitchenProfileId");

                                    b2.ToTable("kitchen_profile");

                                    b2.WithOwner()
                                        .HasForeignKey("WeeklyWorkingHoursKitchenProfileId");
                                });

                            b1.OwnsOne("CampusEats.Api.Models.WorkingHours", "Monday", b2 =>
                                {
                                    b2.Property<Guid>("WeeklyWorkingHoursKitchenProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("Close")
                                        .HasColumnType("interval");

                                    b2.Property<TimeSpan>("Open")
                                        .HasColumnType("interval");

                                    b2.HasKey("WeeklyWorkingHoursKitchenProfileId");

                                    b2.ToTable("kitchen_profile");

                                    b2.WithOwner()
                                        .HasForeignKey("WeeklyWorkingHoursKitchenProfileId");
                                });

                            b1.OwnsOne("CampusEats.Api.Models.WorkingHours", "Saturday", b2 =>
                                {
                                    b2.Property<Guid>("WeeklyWorkingHoursKitchenProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("Close")
                                        .HasColumnType("interval");

                                    b2.Property<TimeSpan>("Open")
                                        .HasColumnType("interval");

                                    b2.HasKey("WeeklyWorkingHoursKitchenProfileId");

                                    b2.ToTable("kitchen_profile");

                                    b2.WithOwner()
                                        .HasForeignKey("WeeklyWorkingHoursKitchenProfileId");
                                });

                            b1.OwnsOne("CampusEats.Api.Models.WorkingHours", "Sunday", b2 =>
                                {
                                    b2.Property<Guid>("WeeklyWorkingHoursKitchenProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("Close")
                                        .HasColumnType("interval");

                                    b2.Property<TimeSpan>("Open")
                                        .HasColumnType("interval");

                                    b2.HasKey("WeeklyWorkingHoursKitchenProfileId");

                                    b2.ToTable("kitchen_profile");

                                    b2.WithOwner()
                                        .HasForeignKey("WeeklyWorkingHoursKitchenProfileId");
                                });

                            b1.OwnsOne("CampusEats.Api.Models.WorkingHours", "Thursday", b2 =>
                                {
                                    b2.Property<Guid>("WeeklyWorkingHoursKitchenProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("Close")
                                        .HasColumnType("interval");

                                    b2.Property<TimeSpan>("Open")
                                        .HasColumnType("interval");

                                    b2.HasKey("WeeklyWorkingHoursKitchenProfileId");

                                    b2.ToTable("kitchen_profile");

                                    b2.WithOwner()
                                        .HasForeignKey("WeeklyWorkingHoursKitchenProfileId");
                                });

                            b1.OwnsOne("CampusEats.Api.Models.WorkingHours", "Tuesday", b2 =>
                                {
                                    b2.Property<Guid>("WeeklyWorkingHoursKitchenProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("Close")
                                        .HasColumnType("interval");

                                    b2.Property<TimeSpan>("Open")
                                        .HasColumnType("interval");

                                    b2.HasKey("WeeklyWorkingHoursKitchenProfileId");

                                    b2.ToTable("kitchen_profile");

                                    b2.WithOwner()
                                        .HasForeignKey("WeeklyWorkingHoursKitchenProfileId");
                                });

                            b1.OwnsOne("CampusEats.Api.Models.WorkingHours", "Wednesday", b2 =>
                                {
                                    b2.Property<Guid>("WeeklyWorkingHoursKitchenProfileId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("Close")
                                        .HasColumnType("interval");

                                    b2.Property<TimeSpan>("Open")
                                        .HasColumnType("interval");

                                    b2.HasKey("WeeklyWorkingHoursKitchenProfileId");

                                    b2.ToTable("kitchen_profile");

                                    b2.WithOwner()
                                        .HasForeignKey("WeeklyWorkingHoursKitchenProfileId");
                                });

                            b1.Navigation("Friday")
                                .IsRequired();

                            b1.Navigation("Monday")
                                .IsRequired();

                            b1.Navigation("Saturday")
                                .IsRequired();

                            b1.Navigation("Sunday")
                                .IsRequired();

                            b1.Navigation("Thursday")
                                .IsRequired();

                            b1.Navigation("Tuesday")
                                .IsRequired();

                            b1.Navigation("Wednesday")
                                .IsRequired();
                        });

                    b.Navigation("KitchenAddress")
                        .IsRequired();

                    b.Navigation("WeeklyWorkingHours")
                        .IsRequired();
                });

            modelBuilder.Entity("CampusEats.Api.Models.KitchenTask", b =>
                {
                    b.HasOne("CampusEats.Api.Models.User", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CampusEats.Api.Models.Order", "Order")
                        .WithOne("KitchenTask")
                        .HasForeignKey("CampusEats.Api.Models.KitchenTask", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedStaff");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CampusEats.Api.Models.LoyaltyAccount", b =>
                {
                    b.HasOne("CampusEats.Api.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("CampusEats.Api.Models.LoyaltyAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusEats.Api.Models.LoyaltyTransaction", b =>
                {
                    b.HasOne("CampusEats.Api.Models.LoyaltyAccount", "LoyaltyAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("LoyaltyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoyaltyAccount");
                });

            modelBuilder.Entity("CampusEats.Api.Models.MenuItemAllergen", b =>
                {
                    b.HasOne("CampusEats.Api.Models.Allergen", "Allergen")
                        .WithMany("MenuItemAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusEats.Api.Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemAllergens")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("CampusEats.Api.Models.Order", b =>
                {
                    b.HasOne("CampusEats.Api.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampusEats.Api.Models.OrderItem", b =>
                {
                    b.HasOne("CampusEats.Api.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CampusEats.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CampusEats.Api.Models.Payment", b =>
                {
                    b.HasOne("CampusEats.Api.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("CampusEats.Api.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CampusEats.Api.Models.Allergen", b =>
                {
                    b.Navigation("MenuItemAllergens");
                });

            modelBuilder.Entity("CampusEats.Api.Models.LoyaltyAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampusEats.Api.Models.MenuItem", b =>
                {
                    b.Navigation("MenuItemAllergens");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CampusEats.Api.Models.Order", b =>
                {
                    b.Navigation("KitchenTask");

                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("CampusEats.Api.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
