name: .NET API PR

on:
  pull_request: {}   # triggers on all PRs regardless of target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./CampusEats.Client/CampusEats.Client.csproj

      - name: Build
        run: dotnet build ./CampusEats.Client/CampusEats.Client.csproj --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal
