name: PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup .NET SDK
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Run Makefile
      - run: make all
