name: React Client PR

on:
  pull_request: {}   # triggers on all PRs regardless of target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./campuseats.client

      - name: Build
        run: npm run build
        working-directory: ./campuseats.client
